// oui.h — HomeSentinel vendor (OUI) lookup
//
// The IEEE OUI database maps the first 3 bytes of a MAC (the Organizationally
// Unique Identifier) to a vendor name. The full list is multiple MB; we ship a
// trimmed, sorted binary blob in a dedicated read-only flash partition ("oui")
// and binary-search it. The blob is generated by tools/build_oui.py from the
// official IEEE source, so anyone can regenerate and verify it.
//
// Blob format (little-endian, packed), produced by build_oui.py:
//   [4 bytes] magic     = "OUI1"
//   [4 bytes] count     = number of records (uint32)
//   then `count` records, each fixed-size and sorted ascending by oui24:
//       [3 bytes] oui24      (MAC bytes 0..2, big-endian as on the wire)
//       [1 byte ] reserved   (alignment / flags)
//       [28 bytes] vendor    (NUL-padded ASCII, truncated)
//   Record size = 32 bytes. Sorted order enables binary search.

#pragma once

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
#include "esp_err.h"

#ifdef __cplusplus
extern "C" {
#endif

#define OUI_VENDOR_LEN   28
#define OUI_RECORD_SIZE  32
#define OUI_MAGIC        "OUI1"

// Map the "oui" partition and validate its header. Safe to call once at boot.
// Returns ESP_ERR_NOT_FOUND if the partition is missing or the magic is wrong
// (e.g. the blob was never flashed) — lookups then return "Unknown".
esp_err_t oui_init(void);

// Look up a vendor by MAC. Writes into out (size out_len, always NUL-term'd).
// Returns true if a vendor was found, false otherwise (out gets "Unknown").
// Randomized/locally-administered MACs short-circuit to "Randomized (private)".
bool oui_lookup(const uint8_t mac[6], char *out, size_t out_len);

#ifdef __cplusplus
}
#endif
