// web.c — HomeSentinel web server

#include "web.h"
#include "inventory.h"
#include "discovery.h"

#include <string.h>
#include <stdio.h>
#include "esp_http_server.h"
#include "esp_log.h"
#include "esp_tls_crypto.h"   // esp_crypto_base64_encode
#include "sdkconfig.h"

static const char *TAG = "web";

// The gzipped UI is embedded by the build (EMBED_FILES in CMakeLists). These
// symbols are generated by the build system from web/index.html.gz.
extern const uint8_t index_html_gz_start[] asm("_binary_index_html_gz_start");
extern const uint8_t index_html_gz_end[]   asm("_binary_index_html_gz_end");

// ---- Basic auth ----------------------------------------------------------
// Build the expected "Basic base64(user:pass)" string once at startup.
static char s_expected_auth[128];

static void build_expected_auth(void)
{
    char creds[96];
    int n = snprintf(creds, sizeof(creds), "%s:%s",
                     CONFIG_HS_WEB_USER, CONFIG_HS_WEB_PASSWORD);

    size_t olen = 0;
    char b64[128];
    esp_crypto_base64_encode((unsigned char *)b64, sizeof(b64), &olen,
                             (const unsigned char *)creds, n);
    snprintf(s_expected_auth, sizeof(s_expected_auth), "Basic %.*s",
             (int)olen, b64);
}

// Returns true if the request carries valid Basic auth.
static bool check_auth(httpd_req_t *req)
{
    size_t len = httpd_req_get_hdr_value_len(req, "Authorization");
    if (len == 0 || len >= 200) {
        return false;
    }
    char buf[208];
    if (httpd_req_get_hdr_value_str(req, "Authorization", buf, sizeof(buf))
        != ESP_OK) {
        return false;
    }
    return strcmp(buf, s_expected_auth) == 0;
}

static esp_err_t send_401(httpd_req_t *req)
{
    httpd_resp_set_status(req, "401 Unauthorized");
    httpd_resp_set_hdr(req, "WWW-Authenticate",
                       "Basic realm=\"HomeSentinel\"");
    httpd_resp_send(req, "Authentication required", HTTPD_RESP_USE_STRLEN);
    return ESP_OK;
}

// Gate helper used at the top of every protected handler.
#define REQUIRE_AUTH(req) do { if (!check_auth(req)) return send_401(req); } while (0)

// ---- Small JSON builder helpers ------------------------------------------
// We stream JSON directly to the response in chunks to avoid building a big
// string in RAM. Each helper appends to a fixed scratch buffer and flushes.

static void dev_class_str(dev_class_t c, char *out, size_t n)
{
    const char *s;
    switch (c) {
        case DEV_CLASS_COMPUTER: s = "computer"; break;
        case DEV_CLASS_MOBILE:   s = "mobile";   break;
        case DEV_CLASS_IOT:      s = "iot";      break;
        case DEV_CLASS_INFRA:    s = "infra";    break;
        default:                 s = "unknown";  break;
    }
    strlcpy(out, s, n);
}

// ---- /api/devices --------------------------------------------------------
static esp_err_t devices_handler(httpd_req_t *req)
{
    REQUIRE_AUTH(req);
    httpd_resp_set_type(req, "application/json");

    httpd_resp_sendstr_chunk(req, "[");

    inv_lock();
    size_t idx = 0;
    device_t *d;
    bool first = true;
    char line[320];
    char cls[12];
    while ((d = inv_next(&idx)) != NULL) {
        dev_class_str(d->dev_class, cls, sizeof(cls));
        int n = snprintf(line, sizeof(line),
            "%s{\"mac\":\"%02X:%02X:%02X:%02X:%02X:%02X\","
            "\"ip\":\"%u.%u.%u.%u\",\"host\":\"%s\",\"vendor\":\"%s\","
            "\"class\":\"%s\",\"online\":%s,\"randomized\":%s,"
            "\"known\":%s,\"first\":%lld,\"last\":%lld}",
            first ? "" : ",",
            d->mac[0],d->mac[1],d->mac[2],d->mac[3],d->mac[4],d->mac[5],
            (unsigned)((d->ip>>24)&0xFF),(unsigned)((d->ip>>16)&0xFF),
            (unsigned)((d->ip>>8)&0xFF),(unsigned)(d->ip&0xFF),
            d->hostname, d->vendor, cls,
            d->online ? "true":"false",
            d->randomized_mac ? "true":"false",
            d->known ? "true":"false",
            (long long)d->first_seen, (long long)d->last_seen);
        if (n > 0 && n < (int)sizeof(line)) {
            httpd_resp_sendstr_chunk(req, line);
            first = false;
        }
    }
    inv_unlock();

    httpd_resp_sendstr_chunk(req, "]");
    httpd_resp_sendstr_chunk(req, NULL);   // end chunked response
    return ESP_OK;
}

// ---- /api/events ---------------------------------------------------------
static const char *ev_type_str(event_type_t t)
{
    switch (t) {
        case EV_NEW_DEVICE:       return "new_device";
        case EV_DEVICE_MISSING:   return "device_missing";
        case EV_DEVICE_RETURNED:  return "device_returned";
        case EV_HOSTNAME_CHANGED: return "hostname_changed";
        case EV_IP_CHANGED:       return "ip_changed";
        case EV_UNKNOWN_VENDOR:   return "unknown_vendor";
        case EV_DEVICE_GROWTH:    return "device_growth";
        case EV_NIGHT_ACTIVITY:   return "night_activity";
        default:                  return "none";
    }
}

static const char *sev_str(severity_t s)
{
    switch (s) {
        case SEV_CRITICAL: return "critical";
        case SEV_WARNING:  return "warning";
        default:           return "info";
    }
}

static esp_err_t events_handler(httpd_req_t *req)
{
    REQUIRE_AUTH(req);
    httpd_resp_set_type(req, "application/json");

    // Copy events out under lock, then serialize unlocked.
    static event_t evbuf[128];
    size_t n;
    inv_lock();
    n = inv_get_events(evbuf, 128);
    inv_unlock();

    httpd_resp_sendstr_chunk(req, "[");
    char line[256];
    for (size_t i = 0; i < n; i++) {
        event_t *e = &evbuf[i];
        // Note: detail is already plain text; escape quotes minimally.
        char safe[120];
        size_t o = 0;
        for (size_t k = 0; e->detail[k] && o + 2 < sizeof(safe); k++) {
            char c = e->detail[k];
            if (c == '"' || c == '\\') safe[o++] = '\\';
            safe[o++] = c;
        }
        safe[o] = '\0';

        int w = snprintf(line, sizeof(line),
            "%s{\"ts\":%lld,\"type\":\"%s\",\"sev\":\"%s\",\"detail\":\"%s\"}",
            i ? "," : "", (long long)e->ts, ev_type_str(e->type),
            sev_str(e->severity), safe);
        if (w > 0 && w < (int)sizeof(line)) {
            httpd_resp_sendstr_chunk(req, line);
        }
    }
    httpd_resp_sendstr_chunk(req, "]");
    httpd_resp_sendstr_chunk(req, NULL);
    return ESP_OK;
}

// ---- /api/stats ----------------------------------------------------------
static esp_err_t stats_handler(httpd_req_t *req)
{
    REQUIRE_AUTH(req);
    httpd_resp_set_type(req, "application/json");

    inv_lock();
    size_t total = inv_count_total();
    size_t online = inv_count_online();
    inv_unlock();

    char body[160];
    snprintf(body, sizeof(body),
        "{\"total\":%u,\"online\":%u,\"offline\":%u,\"last_scan_ms\":%u}",
        (unsigned)total, (unsigned)online, (unsigned)(total - online),
        (unsigned)discovery_last_duration_ms());
    httpd_resp_sendstr(req, body);
    return ESP_OK;
}

// ---- /api/scan (POST) ----------------------------------------------------
static esp_err_t scan_handler(httpd_req_t *req)
{
    REQUIRE_AUTH(req);
    discovery_trigger_now();
    httpd_resp_set_type(req, "application/json");
    httpd_resp_sendstr(req, "{\"ok\":true}");
    return ESP_OK;
}

// ---- / (dashboard) -------------------------------------------------------
static esp_err_t root_handler(httpd_req_t *req)
{
    REQUIRE_AUTH(req);
    const size_t gz_len = index_html_gz_end - index_html_gz_start;
    httpd_resp_set_type(req, "text/html");
    httpd_resp_set_hdr(req, "Content-Encoding", "gzip");
    httpd_resp_send(req, (const char *)index_html_gz_start, gz_len);
    return ESP_OK;
}

// ---- Server startup ------------------------------------------------------
static const httpd_uri_t URIS[] = {
    { .uri = "/",            .method = HTTP_GET,  .handler = root_handler },
    { .uri = "/api/devices", .method = HTTP_GET,  .handler = devices_handler },
    { .uri = "/api/events",  .method = HTTP_GET,  .handler = events_handler },
    { .uri = "/api/stats",   .method = HTTP_GET,  .handler = stats_handler },
    { .uri = "/api/scan",    .method = HTTP_POST, .handler = scan_handler },
};

esp_err_t web_start(void)
{
    build_expected_auth();

    httpd_config_t cfg = HTTPD_DEFAULT_CONFIG();
    cfg.max_uri_handlers = 8;
    cfg.lru_purge_enable = true;
    cfg.stack_size = 8192;

    httpd_handle_t server = NULL;
    esp_err_t err = httpd_start(&server, &cfg);
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "httpd_start failed: %s", esp_err_to_name(err));
        return err;
    }

    for (size_t i = 0; i < sizeof(URIS) / sizeof(URIS[0]); i++) {
        httpd_register_uri_handler(server, &URIS[i]);
    }

    ESP_LOGI(TAG, "web server up on :80");
    return ESP_OK;
}
